name: Send cURL request every 10 minutes

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  curl_request:
    runs-on: ubuntu-latest
    steps:
      - name: Send cURL request to status endpoint
        run: |
          curl -m 60 -X GET "https://rag-backend-zh2e.onrender.com/status" \
          -H "Accept: application/json" \
          -w "\nHTTP Status: %{http_code}\nTime: %{time_total}s\n"